post:
  tags:
    - Additional APIs
  summary: Gets the connector log4net config for the connector.
  parameters:
    - name: proxyId
      in: query
      required: true
      schema:
        type: string
  responses:
    '200':
      description: API-Result
      content:
        '*/*':
          schema:
            $ref: ../components/schemas/CoreGetConnectorLog4NetConfig.yaml
  x-idap-anon: false
