post:
  tags:
    - Additional APIs
  summary: Gets the directory service configuration.
  parameters:
    - name: directoryServiceUuid
      in: query
      description: The unique identifier for the directory service.
      required: true
      schema:
        type: string
  responses:
    '200':
      description: API-Result
      content:
        '*/*':
          schema:
            $ref: >-
              ../components/schemas/GoogleDirectoryGetDirectoryServiceConfig.yaml
  x-idap-anon: false
