post:
  tags:
    - Additional APIs
  summary: Update Progressive Password Migration Configuration
  description: You must be a system administrator or have user management permissions.
  requestBody:
    content:
      application/json:
        schema:
          required:
            - PpmScript
          type: object
          properties:
            PpmScript:
              type: string
              description: PPM Script Text
    required: true
  responses:
    '200':
      description: API-Result
      content:
        '*/*':
          schema:
            $ref: ../components/schemas/PpmUpdatePpmConfig.yaml
  x-idap-anon: false
  x-codegen-request-body-name: payload
