post:
  tags:
    - Additional APIs
  summary: Get the application client secret.
  description: Requires directory service administrator rights.
  requestBody:
    content:
      application/json:
        schema:
          required:
            - ApplicationClientId
            - IdpName
          type: object
          properties:
            ApplicationClientId:
              type: boolean
              description: The application client id.
            IdpName:
              type: string
              description: >-
                The identity provider name (Facebook, Google, Twitter, LinkedIn,
                Microsoft).
    required: true
  responses:
    '200':
      description: API-Result
      content:
        '*/*':
          schema:
            $ref: >-
              ../components/schemas/SocialAuthMgmtGetApplicationClientSecret.yaml
  x-idap-anon: false
  x-codegen-request-body-name: payload
