post:
  tags:
    - Additional APIs
  summary: Reset portal configuration.
  responses:
    '200':
      description: API-Result
      content:
        '*/*':
          schema:
            $ref: ../components/schemas/TenantConfigResetPortalConfig.yaml
  x-idap-anon: false
