post:
  tags:
    - Additional APIs
  summary: Get the tenant Twilio configuration.
  responses:
    '200':
      description: API-Result
      content:
        '*/*':
          schema:
            $ref: ../components/schemas/TenantConfigGetTwilioConfig.yaml
  x-idap-anon: false
