post:
  tags:
    - Additional APIs
  summary: Set password persistance. i.e. do we save your password.
  description: Reserved for on premises environments.
  parameters:
    - name: value
      in: query
      description: >-
        Allow or not the use of active directory credentials for tenant
        applications.
      required: true
      schema:
        type: string
  responses:
    '200':
      description: API-Result
      content:
        '*/*':
          schema:
            $ref: ../components/schemas/TenantConfigSetPasswordPersistance.yaml
  x-idap-anon: false
