post:
  tags:
    - Additional APIs
  summary: Gets the google key for the tenant.
  responses:
    '200':
      description: API-Result
      content:
        '*/*':
          schema:
            $ref: ../components/schemas/TenantConfigGetGoogleKey.yaml
  x-idap-anon: false
