post:
  tags:
    - Additional APIs
  summary: Get the tenant Simple Mail Transport Protocol configuration.
  responses:
    '200':
      description: API-Result
      content:
        '*/*':
          schema:
            $ref: ../components/schemas/TenantConfigGetSMTPConfig.yaml
  x-idap-anon: false
