post:
  tags:
    - Additional APIs
  summary: Gets the tenant mobile configuration data.
  responses:
    '200':
      description: API-Result
      content:
        '*/*':
          schema:
            $ref: ../components/schemas/TenantConfigGetMobileConfig.yaml
  x-idap-anon: false
