type: object
properties:
  Result:
    type: boolean
    description: Did the directory service config update work.
  Error:
    type: object
    description: Error message text on failure, may be null
