type: object
properties:
  Result:
    type: string
    description: The requested key value.
  Error:
    type: object
    properties: {}
    description: |2-

                  {
                      description: "The requested key value.", type: "string"
                  }
                  
