type: object
properties:
  Result:
    type: object
    properties:
      Hostname:
        type: string
        description: The host name of the connector.
      Name:
        type: string
        description: The proxies name.
      HttpPort:
        type: integer
        description: Hyper text transport port number.
      Port:
        type: integer
        description: Port number for the connector.
      Enabled:
        type: boolean
        description: Is the connector enabled.
      WebProxyEnabled:
        type: boolean
        description: Should the web connector be enabled.
      WinNetProxyEnabled:
        type: boolean
        description: >-
          Should the WinNet service (to provision and deprovision users on
          machines) be enabled.
      CertThumbprint:
        type: string
        description: certificate thumbprint
      IwaCheckTimeout:
        type: integer
        description: The Iwa timeout value to use.
      WebProxyPort:
        type: integer
        description: The port used by the web connector.
    description: The connector that got set
  Error:
    type: object
    description: Error message text on failure, may be null
