type: object
properties:
  Result:
    type: array
    description: The connector Iwa settings.
    items:
      type: object
      properties: {}
  Error:
    type: object
    description: Error message text on failure, may be null
