type: object
properties:
  Result:
    type: object
    properties: {}
    description: The LDAP service that was just added.
  Error:
    type: object
    description: Error message text on failure, may be null
