type: object
properties:
  Result:
    type: object
    properties:
      Port:
        type: integer
        description: Listen port
      ReceiveTimeout:
        type: integer
        description: receive timeout in millseconds
      Enabled:
        type: boolean
        description: Is radius enabled
    description: Radius connector config information
  Error:
    type: object
    description: Error message text on failure, may be null
