type: object
properties:
  Result:
    type: object
    properties:
      _RowKey:
        type: string
        description: Application key
      success:
        type: boolean
        description: Whether the operation is successful
    description: Result
  Error:
    type: object
    description: Error message text on failure, may be null
