type: object
properties:
  Result:
    type: object
    properties:
      _RowKey:
        type: string
        description: Application ID
      Url:
        type: string
        description: Application Url
      AdminTag:
        type: string
        description: Application admin tag
      Description:
        type: string
        description: Application description
      Category:
        type: string
        description: Application category
      Name:
        type: string
        description: Application name
      Reference:
        type: integer
        description: Reference ID of this application template
      Generic:
        type: boolean
        description: Whether application is a generic application
      UseDefaultSigningCert:
        type: boolean
        description: Whether to use the default signing certificate
      TemplateName:
        type: string
        description: Application template name
      UserPassScript:
        type: string
        description: UserPass script
      PasswordIsSet:
        type: boolean
        description: Whether the password has been set
      WebAppType:
        type: string
        description: Application web-app-type
      UserNameStrategy:
        type: string
        description: Strategy for mapping username
      DisplayName:
        type: string
        description: Application display name
      AdminPasswordIsSet:
        type: boolean
        description: Whether admin password has been set
      State:
        type: string
        description: Application state
      AppTypeDisplayName:
        type: string
        description: Display name of application type
      AppType:
        type: string
        description: Application type
      Thumbprint:
        type: string
        description: Certificate thumbprint
      Handler:
        type: string
        description: Application handler
      Icon:
        type: string
        description: Path of application icon image
      CertificateSubjectName:
        type: string
        description: Certificate subject name
    description: A list of applications
  Error:
    type: object
    description: Error message text on failure, may be null
