type: object
properties:
  Result:
    type: object
    properties:
      ApplicationClientId:
        type: string
        description: The application client id.
      ApplicationClientSecret:
        type: string
        description: The application client secret.
      IdpName:
        type: string
        description: The identity provider name.
    description: The applicaiton client secret.
  Error:
    type: object
    description: Error message text on failure, may be null
