type: object
properties:
  Result:
    type: object
    properties:
      Threshold:
        type: integer
        description: Threshold
      Emails:
        type: string
        description: Emails
    description: The tenant Telephony Credits Notification configuration.
  Error:
    type: object
    description: Error message text on failure, may be null
