type: object
properties:
  Result:
    type: boolean
    description: Did the tenant configuration key value get set.
  Error:
    type: object
    description: Error message text on failure, may be null
