type: object
properties:
  ErrorID:
    type: string
    description: Unique support identifier for this occurrence of an error
  Result:
    type: object
    properties:
      IsGatewayed:
        type: boolean
        description: ''
      GatewayTunnelCertSslException:
        type: string
        description: The gateway tunnel certificate security socket layer exception.
      GatewayHost:
        type: string
        description: The gateway host.
      GatewayTunnelIsSsl:
        type: boolean
        description: Is the gateway tunnel ssl enabled.
      GatewayTunnelCertExpDate:
        type: string
        description: The gateway tunnel certificate expiration date.
      GatewayCertThumbprint:
        type: string
        description: The gateway certificate thumprint.
      GatewayCertExpirationDate:
        type: string
        description: The gateway certificate expiration date.
      GatewayCertSubject:
        type: string
        description: The gateway certificate subject.
      GatewayHostValidated:
        type: boolean
        description: Is the gateway host validated.
      ShadowAppLink:
        type: string
        description: The shadow application link.
      GatewayTunnelCertThumbprint:
        type: string
        description: The gateway tunnel certificate thumbprint.
      CName:
        type: string
        description: The application cname.
    description: The gateway configuration for application A.
  Message:
    type: string
    description: Error message text on failure, may be null
  success:
    type: boolean
    description: Indicates API success or failure
