type: object
properties:
  Result:
    type: boolean
    description: Did the LDAP directory service config verify.
  Error:
    type: object
    description: Error message text on failure, may be null
