type: object
properties:
  Result:
    type: object
    properties:
      EnableMicrosoftLogin:
        type: boolean
        description: Is Microsoft login enabled.
      Version:
        type: string
        description: The configuration version.
      EnableTwitterLogin:
        type: boolean
        description: Is Twitter login enabled.
      EnableGoogleLogin:
        type: boolean
        description: Is Google login enabled.
      EnableLinkedInLogin:
        type: boolean
        description: Is LinkedIn login enabled.
      EnableFacebookLogin:
        type: boolean
        description: Is Facebook login enabled.
    description: The social user authentication configuration.
  Error:
    type: object
    description: Error message text on failure, may be null
