type: object
properties:
  Result:
    type: object
    properties:
      DisplayType:
        type: string
        description: The message template display type.
      Substitutions:
        type: array
        description: A list of substitutable templates.
        items:
          type: object
          properties: {}
      TemplateName:
        type: string
        description: The template name.
      Type:
        type: string
        description: The message template type.
      ModifiedLanguages:
        type: array
        description: A list of languages available for the message template.
        items:
          type: string
      Name:
        type: string
        description: The message template name.
    description: An editable message template.
  Error:
    type: object
    description: Error message text on failure, may be null
